# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.21.340
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import controlm_py
from controlm_py.models.configuration_manager_privilege_category import ConfigurationManagerPrivilegeCategory  # noqa: E501
from controlm_py.rest import ApiException


class TestConfigurationManagerPrivilegeCategory(unittest.TestCase):
    """ConfigurationManagerPrivilegeCategory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfigurationManagerPrivilegeCategory(self):
        """Test ConfigurationManagerPrivilegeCategory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = controlm_py.models.configuration_manager_privilege_category.ConfigurationManagerPrivilegeCategory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
