# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.21.340
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import controlm_py
from controlm_py.models.em_order_folder_parameters import EmOrderFolderParameters  # noqa: E501
from controlm_py.rest import ApiException


class TestEmOrderFolderParameters(unittest.TestCase):
    """EmOrderFolderParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmOrderFolderParameters(self):
        """Test EmOrderFolderParameters"""
        # FIXME: construct object with mandatory attributes with example values
        # model = controlm_py.models.em_order_folder_parameters.EmOrderFolderParameters()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
