# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.20.40
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.component_key_with_status_type import ComponentKeyWithStatusType  # noqa: E501
from swagger_client.rest import ApiException


class TestComponentKeyWithStatusType(unittest.TestCase):
    """ComponentKeyWithStatusType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComponentKeyWithStatusType(self):
        """Test ComponentKeyWithStatusType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.component_key_with_status_type.ComponentKeyWithStatusType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
