# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.20.40
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.zos_template_data import ZosTemplateData  # noqa: E501
from swagger_client.rest import ApiException


class TestZosTemplateData(unittest.TestCase):
    """ZosTemplateData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testZosTemplateData(self):
        """Test ZosTemplateData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.zos_template_data.ZosTemplateData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
