# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.20.40
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.deploy_api import DeployApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDeployApi(unittest.TestCase):
    """DeployApi unit test stubs"""

    def setUp(self):
        self.api = DeployApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_calendar(self):
        """Test case for delete_calendar

        delete a calendar  # noqa: E501
        """
        pass

    def test_delete_connection_profile(self):
        """Test case for delete_connection_profile

        Delete Local Connection Profile  # noqa: E501
        """
        pass

    def test_delete_folder(self):
        """Test case for delete_folder

        delete a folder  # noqa: E501
        """
        pass

    def test_delete_local_connection_profile(self):
        """Test case for delete_local_connection_profile

        Delete Local Connection Profile  # noqa: E501
        """
        pass

    def test_delete_shared_connection_profile(self):
        """Test case for delete_shared_connection_profile

        Delete centralized Connection Profile  # noqa: E501
        """
        pass

    def test_deploy_ai_jobtype(self):
        """Test case for deploy_ai_jobtype

        Deploy of Application Integrator job type.  # noqa: E501
        """
        pass

    def test_deploy_file(self):
        """Test case for deploy_file

        Deploy definitions file  # noqa: E501
        """
        pass

    def test_get_connection_profiles_deployment_status(self):
        """Test case for get_connection_profiles_deployment_status

        Get deployed connection profiles deployment status  # noqa: E501
        """
        pass

    def test_get_deployed_ai_jobtypes(self):
        """Test case for get_deployed_ai_jobtypes

        Get Application Integrator job types  # noqa: E501
        """
        pass

    def test_get_deployed_calendars(self):
        """Test case for get_deployed_calendars

        Get deployed calendars that match the search criteria.  # noqa: E501
        """
        pass

    def test_get_deployed_connection_profiles(self):
        """Test case for get_deployed_connection_profiles

        Get local deployed connection profiles  # noqa: E501
        """
        pass

    def test_get_deployed_connection_profiles_status(self):
        """Test case for get_deployed_connection_profiles_status

        Get deployed connection profiles status  # noqa: E501
        """
        pass

    def test_get_deployed_folders_new(self):
        """Test case for get_deployed_folders_new

        Get deployed jobs that match the search criteria.  # noqa: E501
        """
        pass

    def test_get_local_connection_profiles(self):
        """Test case for get_local_connection_profiles

        Get local deployed connection profiles  # noqa: E501
        """
        pass

    def test_get_shared_connection_profiles(self):
        """Test case for get_shared_connection_profiles

        Get centralized deployed connection profile  # noqa: E501
        """
        pass

    def test_get_site_standard_field_restrictions(self):
        """Test case for get_site_standard_field_restrictions

        Get the allowed values for the specified field in the specified site standard.  # noqa: E501
        """
        pass

    def test_set_site_standard_field_restrictions(self):
        """Test case for set_site_standard_field_restrictions

        Replace the allowed values for the specified field in the specified site standard.  # noqa: E501
        """
        pass

    def test_test_connection_profile(self):
        """Test case for test_connection_profile

        Test connection profile on agent  # noqa: E501
        """
        pass

    def test_transform_file(self):
        """Test case for transform_file

        Transform a definitions file  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
