# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.21.340
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import controlm_py
from controlm_py.api.session_api import SessionApi  # noqa: E501
from controlm_py.rest import ApiException


class TestSessionApi(unittest.TestCase):
    """SessionApi unit test stubs"""

    def setUp(self):
        self.api = SessionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_do_login(self):
        """Test case for do_login

        login user to Control-M  # noqa: E501
        """
        pass

    def test_do_logout(self):
        """Test case for do_logout

        logout user from Control-M  # noqa: E501
        """
        pass

    def test_update_my_password(self):
        """Test case for update_my_password

        Change my password  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
