# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.21.340
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import controlm_py
from controlm_py.models.fts_ldap_authentication_details import FtsLdapAuthenticationDetails  # noqa: E501
from controlm_py.rest import ApiException


class TestFtsLdapAuthenticationDetails(unittest.TestCase):
    """FtsLdapAuthenticationDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFtsLdapAuthenticationDetails(self):
        """Test FtsLdapAuthenticationDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = controlm_py.models.fts_ldap_authentication_details.FtsLdapAuthenticationDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
