# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.20.40
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.set_agent_params import SetAgentParams  # noqa: E501
from swagger_client.rest import ApiException


class TestSetAgentParams(unittest.TestCase):
    """SetAgentParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSetAgentParams(self):
        """Test SetAgentParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.set_agent_params.SetAgentParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
