# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.20.40
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.fts_sftp_settings import FtsSftpSettings  # noqa: E501
from swagger_client.rest import ApiException


class TestFtsSftpSettings(unittest.TestCase):
    """FtsSftpSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFtsSftpSettings(self):
        """Test FtsSftpSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.fts_sftp_settings.FtsSftpSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
