# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.21.340
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import controlm_py
from controlm_py.models.agent_details import AgentDetails  # noqa: E501
from controlm_py.rest import ApiException


class TestAgentDetails(unittest.TestCase):
    """AgentDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAgentDetails(self):
        """Test AgentDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = controlm_py.models.agent_details.AgentDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
