# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.21.340
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import controlm_py
from controlm_py.api.archive_api import ArchiveApi  # noqa: E501
from controlm_py.rest import ApiException


class TestArchiveApi(unittest.TestCase):
    """ArchiveApi unit test stubs"""

    def setUp(self):
        self.api = ArchiveApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_archive_job_log(self):
        """Test case for get_archive_job_log

        Get job log  # noqa: E501
        """
        pass

    def test_get_archive_job_output(self):
        """Test case for get_archive_job_output

        Get job output  # noqa: E501
        """
        pass

    def test_search_jobs(self):
        """Test case for search_jobs

        Search jobs in Archive  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
