# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.20.40
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.folders_users_settings_and_metadata_properties_from_b2_b import FoldersUsersSettingsAndMetadataPropertiesFromB2B  # noqa: E501
from swagger_client.rest import ApiException


class TestFoldersUsersSettingsAndMetadataPropertiesFromB2B(unittest.TestCase):
    """FoldersUsersSettingsAndMetadataPropertiesFromB2B unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFoldersUsersSettingsAndMetadataPropertiesFromB2B(self):
        """Test FoldersUsersSettingsAndMetadataPropertiesFromB2B"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.folders_users_settings_and_metadata_properties_from_b2_b.FoldersUsersSettingsAndMetadataPropertiesFromB2B()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
