# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.21.340
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import controlm_py
from controlm_py.models.ctm_advanced_details import CtmAdvancedDetails  # noqa: E501
from controlm_py.rest import ApiException


class TestCtmAdvancedDetails(unittest.TestCase):
    """CtmAdvancedDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCtmAdvancedDetails(self):
        """Test CtmAdvancedDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = controlm_py.models.ctm_advanced_details.CtmAdvancedDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
