# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.21.340
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ActionFailsBehaviourData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'delete_file': 'bool',
        'next_action_behaviour': 'str'
    }

    attribute_map = {
        'delete_file': 'deleteFile',
        'next_action_behaviour': 'nextActionBehaviour'
    }

    def __init__(self, delete_file=None, next_action_behaviour='Abort'):  # noqa: E501
        """ActionFailsBehaviourData - a model defined in Swagger"""  # noqa: E501
        self._delete_file = None
        self._next_action_behaviour = None
        self.discriminator = None
        if delete_file is not None:
            self.delete_file = delete_file
        if next_action_behaviour is not None:
            self.next_action_behaviour = next_action_behaviour

    @property
    def delete_file(self):
        """Gets the delete_file of this ActionFailsBehaviourData.  # noqa: E501

        is delete file  # noqa: E501

        :return: The delete_file of this ActionFailsBehaviourData.  # noqa: E501
        :rtype: bool
        """
        return self._delete_file

    @delete_file.setter
    def delete_file(self, delete_file):
        """Sets the delete_file of this ActionFailsBehaviourData.

        is delete file  # noqa: E501

        :param delete_file: The delete_file of this ActionFailsBehaviourData.  # noqa: E501
        :type: bool
        """

        self._delete_file = delete_file

    @property
    def next_action_behaviour(self):
        """Gets the next_action_behaviour of this ActionFailsBehaviourData.  # noqa: E501

        next action behaviour  # noqa: E501

        :return: The next_action_behaviour of this ActionFailsBehaviourData.  # noqa: E501
        :rtype: str
        """
        return self._next_action_behaviour

    @next_action_behaviour.setter
    def next_action_behaviour(self, next_action_behaviour):
        """Sets the next_action_behaviour of this ActionFailsBehaviourData.

        next action behaviour  # noqa: E501

        :param next_action_behaviour: The next_action_behaviour of this ActionFailsBehaviourData.  # noqa: E501
        :type: str
        """

        self._next_action_behaviour = next_action_behaviour

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ActionFailsBehaviourData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ActionFailsBehaviourData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
