# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.21.340
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConfigSystemsettingsBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'systemsetting': 'str',
        'saml2metadatafile': 'str'
    }

    attribute_map = {
        'systemsetting': 'systemsetting',
        'saml2metadatafile': 'saml2metadatafile'
    }

    def __init__(self, systemsetting=None, saml2metadatafile=None):  # noqa: E501
        """ConfigSystemsettingsBody - a model defined in Swagger"""  # noqa: E501
        self._systemsetting = None
        self._saml2metadatafile = None
        self.discriminator = None
        self.systemsetting = systemsetting
        if saml2metadatafile is not None:
            self.saml2metadatafile = saml2metadatafile

    @property
    def systemsetting(self):
        """Gets the systemsetting of this ConfigSystemsettingsBody.  # noqa: E501

        System Setting JSON file  # noqa: E501

        :return: The systemsetting of this ConfigSystemsettingsBody.  # noqa: E501
        :rtype: str
        """
        return self._systemsetting

    @systemsetting.setter
    def systemsetting(self, systemsetting):
        """Sets the systemsetting of this ConfigSystemsettingsBody.

        System Setting JSON file  # noqa: E501

        :param systemsetting: The systemsetting of this ConfigSystemsettingsBody.  # noqa: E501
        :type: str
        """
        if systemsetting is None:
            raise ValueError("Invalid value for `systemsetting`, must not be `None`")  # noqa: E501

        self._systemsetting = systemsetting

    @property
    def saml2metadatafile(self):
        """Gets the saml2metadatafile of this ConfigSystemsettingsBody.  # noqa: E501

        SAML2 Identity Provider Metadata file to upload  # noqa: E501

        :return: The saml2metadatafile of this ConfigSystemsettingsBody.  # noqa: E501
        :rtype: str
        """
        return self._saml2metadatafile

    @saml2metadatafile.setter
    def saml2metadatafile(self, saml2metadatafile):
        """Sets the saml2metadatafile of this ConfigSystemsettingsBody.

        SAML2 Identity Provider Metadata file to upload  # noqa: E501

        :param saml2metadatafile: The saml2metadatafile of this ConfigSystemsettingsBody.  # noqa: E501
        :type: str
        """

        self._saml2metadatafile = saml2metadatafile

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConfigSystemsettingsBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConfigSystemsettingsBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
