# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.21.340
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CtmSecEntitySecAttrType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'add': 'str',
        'delete': 'str',
        'update': 'str'
    }

    attribute_map = {
        'add': 'Add',
        'delete': 'Delete',
        'update': 'Update'
    }

    def __init__(self, add=None, delete=None, update=None):  # noqa: E501
        """CtmSecEntitySecAttrType - a model defined in Swagger"""  # noqa: E501
        self._add = None
        self._delete = None
        self._update = None
        self.discriminator = None
        if add is not None:
            self.add = add
        if delete is not None:
            self.delete = delete
        if update is not None:
            self.update = update

    @property
    def add(self):
        """Gets the add of this CtmSecEntitySecAttrType.  # noqa: E501

        Values  Y N D for Yes No Default  # noqa: E501

        :return: The add of this CtmSecEntitySecAttrType.  # noqa: E501
        :rtype: str
        """
        return self._add

    @add.setter
    def add(self, add):
        """Sets the add of this CtmSecEntitySecAttrType.

        Values  Y N D for Yes No Default  # noqa: E501

        :param add: The add of this CtmSecEntitySecAttrType.  # noqa: E501
        :type: str
        """

        self._add = add

    @property
    def delete(self):
        """Gets the delete of this CtmSecEntitySecAttrType.  # noqa: E501

        Values  Y N D for Yes No Default  # noqa: E501

        :return: The delete of this CtmSecEntitySecAttrType.  # noqa: E501
        :rtype: str
        """
        return self._delete

    @delete.setter
    def delete(self, delete):
        """Sets the delete of this CtmSecEntitySecAttrType.

        Values  Y N D for Yes No Default  # noqa: E501

        :param delete: The delete of this CtmSecEntitySecAttrType.  # noqa: E501
        :type: str
        """

        self._delete = delete

    @property
    def update(self):
        """Gets the update of this CtmSecEntitySecAttrType.  # noqa: E501

        Values  Y N D for Yes No Default  # noqa: E501

        :return: The update of this CtmSecEntitySecAttrType.  # noqa: E501
        :rtype: str
        """
        return self._update

    @update.setter
    def update(self, update):
        """Sets the update of this CtmSecEntitySecAttrType.

        Values  Y N D for Yes No Default  # noqa: E501

        :param update: The update of this CtmSecEntitySecAttrType.  # noqa: E501
        :type: str
        """

        self._update = update

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CtmSecEntitySecAttrType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CtmSecEntitySecAttrType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
