# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.21.325
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from controlm_py.models.ctm_server_definition import CtmServerDefinition  # noqa: F401,E501

class CtmServerDetails(CtmServerDefinition):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'saving_mode': 'str',
        'message': 'str',
        'services_message': 'str',
        'state': 'str',
        'status': 'str',
        'os_type': 'str',
        'is_paused': 'bool',
        'last_update': 'str',
        'is_high_availability_enabled': 'bool',
        'admin_agent_status': 'str',
        'non_active_ca_status': 'str',
        'primary_host': 'str',
        'secondary_host': 'str',
        'fail_over_mode': 'str',
        'high_availability_process_name': 'str',
        'high_availability_status': 'str',
        'is_db_manager': 'str',
        'last_high_availability_process_date': 'str',
        'additional_attributes': 'list[AdditionalAttribute]',
        'services': 'list[CtmService]',
        'database_def': 'DatabaseDef'
    }
    if hasattr(CtmServerDefinition, "swagger_types"):
        swagger_types.update(CtmServerDefinition.swagger_types)

    attribute_map = {
        'saving_mode': 'savingMode',
        'message': 'message',
        'services_message': 'servicesMessage',
        'state': 'state',
        'status': 'status',
        'os_type': 'osType',
        'is_paused': 'isPaused',
        'last_update': 'lastUpdate',
        'is_high_availability_enabled': 'isHighAvailabilityEnabled',
        'admin_agent_status': 'adminAgentStatus',
        'non_active_ca_status': 'nonActiveCAStatus',
        'primary_host': 'primaryHost',
        'secondary_host': 'secondaryHost',
        'fail_over_mode': 'failOverMode',
        'high_availability_process_name': 'highAvailabilityProcessName',
        'high_availability_status': 'highAvailabilityStatus',
        'is_db_manager': 'isDBManager',
        'last_high_availability_process_date': 'lastHighAvailabilityProcessDate',
        'additional_attributes': 'additionalAttributes',
        'services': 'services',
        'database_def': 'databaseDef'
    }
    if hasattr(CtmServerDefinition, "attribute_map"):
        attribute_map.update(CtmServerDefinition.attribute_map)

    def __init__(self, saving_mode=None, message=None, services_message=None, state=None, status=None, os_type=None, is_paused=None, last_update=None, is_high_availability_enabled=None, admin_agent_status=None, non_active_ca_status=None, primary_host=None, secondary_host=None, fail_over_mode=None, high_availability_process_name=None, high_availability_status=None, is_db_manager=None, last_high_availability_process_date=None, additional_attributes=None, services=None, database_def=None, *args, **kwargs):  # noqa: E501
        """CtmServerDetails - a model defined in Swagger"""  # noqa: E501
        self._saving_mode = None
        self._message = None
        self._services_message = None
        self._state = None
        self._status = None
        self._os_type = None
        self._is_paused = None
        self._last_update = None
        self._is_high_availability_enabled = None
        self._admin_agent_status = None
        self._non_active_ca_status = None
        self._primary_host = None
        self._secondary_host = None
        self._fail_over_mode = None
        self._high_availability_process_name = None
        self._high_availability_status = None
        self._is_db_manager = None
        self._last_high_availability_process_date = None
        self._additional_attributes = None
        self._services = None
        self._database_def = None
        self.discriminator = None
        if saving_mode is not None:
            self.saving_mode = saving_mode
        if message is not None:
            self.message = message
        if services_message is not None:
            self.services_message = services_message
        if state is not None:
            self.state = state
        if status is not None:
            self.status = status
        if os_type is not None:
            self.os_type = os_type
        if is_paused is not None:
            self.is_paused = is_paused
        if last_update is not None:
            self.last_update = last_update
        if is_high_availability_enabled is not None:
            self.is_high_availability_enabled = is_high_availability_enabled
        if admin_agent_status is not None:
            self.admin_agent_status = admin_agent_status
        if non_active_ca_status is not None:
            self.non_active_ca_status = non_active_ca_status
        if primary_host is not None:
            self.primary_host = primary_host
        if secondary_host is not None:
            self.secondary_host = secondary_host
        if fail_over_mode is not None:
            self.fail_over_mode = fail_over_mode
        if high_availability_process_name is not None:
            self.high_availability_process_name = high_availability_process_name
        if high_availability_status is not None:
            self.high_availability_status = high_availability_status
        if is_db_manager is not None:
            self.is_db_manager = is_db_manager
        if last_high_availability_process_date is not None:
            self.last_high_availability_process_date = last_high_availability_process_date
        if additional_attributes is not None:
            self.additional_attributes = additional_attributes
        if services is not None:
            self.services = services
        if database_def is not None:
            self.database_def = database_def
        CtmServerDefinition.__init__(self, *args, **kwargs)

    @property
    def saving_mode(self):
        """Gets the saving_mode of this CtmServerDetails.  # noqa: E501

        Saving Mode property determines what is the current status for the connection with Configuration Agent  # noqa: E501

        :return: The saving_mode of this CtmServerDetails.  # noqa: E501
        :rtype: str
        """
        return self._saving_mode

    @saving_mode.setter
    def saving_mode(self, saving_mode):
        """Sets the saving_mode of this CtmServerDetails.

        Saving Mode property determines what is the current status for the connection with Configuration Agent  # noqa: E501

        :param saving_mode: The saving_mode of this CtmServerDetails.  # noqa: E501
        :type: str
        """

        self._saving_mode = saving_mode

    @property
    def message(self):
        """Gets the message of this CtmServerDetails.  # noqa: E501

        Control-M/Server message describing the communication status  # noqa: E501

        :return: The message of this CtmServerDetails.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this CtmServerDetails.

        Control-M/Server message describing the communication status  # noqa: E501

        :param message: The message of this CtmServerDetails.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def services_message(self):
        """Gets the services_message of this CtmServerDetails.  # noqa: E501

        Control-M/Server services message  # noqa: E501

        :return: The services_message of this CtmServerDetails.  # noqa: E501
        :rtype: str
        """
        return self._services_message

    @services_message.setter
    def services_message(self, services_message):
        """Sets the services_message of this CtmServerDetails.

        Control-M/Server services message  # noqa: E501

        :param services_message: The services_message of this CtmServerDetails.  # noqa: E501
        :type: str
        """

        self._services_message = services_message

    @property
    def state(self):
        """Gets the state of this CtmServerDetails.  # noqa: E501

        Control-M/Server state [up|down]. (Actual State)  # noqa: E501

        :return: The state of this CtmServerDetails.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this CtmServerDetails.

        Control-M/Server state [up|down]. (Actual State)  # noqa: E501

        :param state: The state of this CtmServerDetails.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def status(self):
        """Gets the status of this CtmServerDetails.  # noqa: E501

        Calculated Control-M/Server status  # noqa: E501

        :return: The status of this CtmServerDetails.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this CtmServerDetails.

        Calculated Control-M/Server status  # noqa: E501

        :param status: The status of this CtmServerDetails.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def os_type(self):
        """Gets the os_type of this CtmServerDetails.  # noqa: E501

        Control-M/Server operating system  # noqa: E501

        :return: The os_type of this CtmServerDetails.  # noqa: E501
        :rtype: str
        """
        return self._os_type

    @os_type.setter
    def os_type(self, os_type):
        """Sets the os_type of this CtmServerDetails.

        Control-M/Server operating system  # noqa: E501

        :param os_type: The os_type of this CtmServerDetails.  # noqa: E501
        :type: str
        """

        self._os_type = os_type

    @property
    def is_paused(self):
        """Gets the is_paused of this CtmServerDetails.  # noqa: E501

        Indicates if Control-M/Server is paused  # noqa: E501

        :return: The is_paused of this CtmServerDetails.  # noqa: E501
        :rtype: bool
        """
        return self._is_paused

    @is_paused.setter
    def is_paused(self, is_paused):
        """Sets the is_paused of this CtmServerDetails.

        Indicates if Control-M/Server is paused  # noqa: E501

        :param is_paused: The is_paused of this CtmServerDetails.  # noqa: E501
        :type: bool
        """

        self._is_paused = is_paused

    @property
    def last_update(self):
        """Gets the last_update of this CtmServerDetails.  # noqa: E501

        The Control-M/Server last updated date  # noqa: E501

        :return: The last_update of this CtmServerDetails.  # noqa: E501
        :rtype: str
        """
        return self._last_update

    @last_update.setter
    def last_update(self, last_update):
        """Sets the last_update of this CtmServerDetails.

        The Control-M/Server last updated date  # noqa: E501

        :param last_update: The last_update of this CtmServerDetails.  # noqa: E501
        :type: str
        """

        self._last_update = last_update

    @property
    def is_high_availability_enabled(self):
        """Gets the is_high_availability_enabled of this CtmServerDetails.  # noqa: E501

        Indicates if High Availability is installed  # noqa: E501

        :return: The is_high_availability_enabled of this CtmServerDetails.  # noqa: E501
        :rtype: bool
        """
        return self._is_high_availability_enabled

    @is_high_availability_enabled.setter
    def is_high_availability_enabled(self, is_high_availability_enabled):
        """Sets the is_high_availability_enabled of this CtmServerDetails.

        Indicates if High Availability is installed  # noqa: E501

        :param is_high_availability_enabled: The is_high_availability_enabled of this CtmServerDetails.  # noqa: E501
        :type: bool
        """

        self._is_high_availability_enabled = is_high_availability_enabled

    @property
    def admin_agent_status(self):
        """Gets the admin_agent_status of this CtmServerDetails.  # noqa: E501

        Status of configuration agent on active host  # noqa: E501

        :return: The admin_agent_status of this CtmServerDetails.  # noqa: E501
        :rtype: str
        """
        return self._admin_agent_status

    @admin_agent_status.setter
    def admin_agent_status(self, admin_agent_status):
        """Sets the admin_agent_status of this CtmServerDetails.

        Status of configuration agent on active host  # noqa: E501

        :param admin_agent_status: The admin_agent_status of this CtmServerDetails.  # noqa: E501
        :type: str
        """

        self._admin_agent_status = admin_agent_status

    @property
    def non_active_ca_status(self):
        """Gets the non_active_ca_status of this CtmServerDetails.  # noqa: E501

        Status of configuration agent on non-active host  # noqa: E501

        :return: The non_active_ca_status of this CtmServerDetails.  # noqa: E501
        :rtype: str
        """
        return self._non_active_ca_status

    @non_active_ca_status.setter
    def non_active_ca_status(self, non_active_ca_status):
        """Sets the non_active_ca_status of this CtmServerDetails.

        Status of configuration agent on non-active host  # noqa: E501

        :param non_active_ca_status: The non_active_ca_status of this CtmServerDetails.  # noqa: E501
        :type: str
        """

        self._non_active_ca_status = non_active_ca_status

    @property
    def primary_host(self):
        """Gets the primary_host of this CtmServerDetails.  # noqa: E501

        Primary host  # noqa: E501

        :return: The primary_host of this CtmServerDetails.  # noqa: E501
        :rtype: str
        """
        return self._primary_host

    @primary_host.setter
    def primary_host(self, primary_host):
        """Sets the primary_host of this CtmServerDetails.

        Primary host  # noqa: E501

        :param primary_host: The primary_host of this CtmServerDetails.  # noqa: E501
        :type: str
        """

        self._primary_host = primary_host

    @property
    def secondary_host(self):
        """Gets the secondary_host of this CtmServerDetails.  # noqa: E501

        Secondary Host  # noqa: E501

        :return: The secondary_host of this CtmServerDetails.  # noqa: E501
        :rtype: str
        """
        return self._secondary_host

    @secondary_host.setter
    def secondary_host(self, secondary_host):
        """Sets the secondary_host of this CtmServerDetails.

        Secondary Host  # noqa: E501

        :param secondary_host: The secondary_host of this CtmServerDetails.  # noqa: E501
        :type: str
        """

        self._secondary_host = secondary_host

    @property
    def fail_over_mode(self):
        """Gets the fail_over_mode of this CtmServerDetails.  # noqa: E501

        High Availability fail over mode [Manual, Automatic]  # noqa: E501

        :return: The fail_over_mode of this CtmServerDetails.  # noqa: E501
        :rtype: str
        """
        return self._fail_over_mode

    @fail_over_mode.setter
    def fail_over_mode(self, fail_over_mode):
        """Sets the fail_over_mode of this CtmServerDetails.

        High Availability fail over mode [Manual, Automatic]  # noqa: E501

        :param fail_over_mode: The fail_over_mode of this CtmServerDetails.  # noqa: E501
        :type: str
        """

        self._fail_over_mode = fail_over_mode

    @property
    def high_availability_process_name(self):
        """Gets the high_availability_process_name of this CtmServerDetails.  # noqa: E501

        High Availability process name  # noqa: E501

        :return: The high_availability_process_name of this CtmServerDetails.  # noqa: E501
        :rtype: str
        """
        return self._high_availability_process_name

    @high_availability_process_name.setter
    def high_availability_process_name(self, high_availability_process_name):
        """Sets the high_availability_process_name of this CtmServerDetails.

        High Availability process name  # noqa: E501

        :param high_availability_process_name: The high_availability_process_name of this CtmServerDetails.  # noqa: E501
        :type: str
        """

        self._high_availability_process_name = high_availability_process_name

    @property
    def high_availability_status(self):
        """Gets the high_availability_status of this CtmServerDetails.  # noqa: E501

        The server high availability status  # noqa: E501

        :return: The high_availability_status of this CtmServerDetails.  # noqa: E501
        :rtype: str
        """
        return self._high_availability_status

    @high_availability_status.setter
    def high_availability_status(self, high_availability_status):
        """Sets the high_availability_status of this CtmServerDetails.

        The server high availability status  # noqa: E501

        :param high_availability_status: The high_availability_status of this CtmServerDetails.  # noqa: E501
        :type: str
        """

        self._high_availability_status = high_availability_status

    @property
    def is_db_manager(self):
        """Gets the is_db_manager of this CtmServerDetails.  # noqa: E501

        The server high availability status  # noqa: E501

        :return: The is_db_manager of this CtmServerDetails.  # noqa: E501
        :rtype: str
        """
        return self._is_db_manager

    @is_db_manager.setter
    def is_db_manager(self, is_db_manager):
        """Sets the is_db_manager of this CtmServerDetails.

        The server high availability status  # noqa: E501

        :param is_db_manager: The is_db_manager of this CtmServerDetails.  # noqa: E501
        :type: str
        """

        self._is_db_manager = is_db_manager

    @property
    def last_high_availability_process_date(self):
        """Gets the last_high_availability_process_date of this CtmServerDetails.  # noqa: E501

        Last high availability Manual/Automatic Failover/Fallback date  # noqa: E501

        :return: The last_high_availability_process_date of this CtmServerDetails.  # noqa: E501
        :rtype: str
        """
        return self._last_high_availability_process_date

    @last_high_availability_process_date.setter
    def last_high_availability_process_date(self, last_high_availability_process_date):
        """Sets the last_high_availability_process_date of this CtmServerDetails.

        Last high availability Manual/Automatic Failover/Fallback date  # noqa: E501

        :param last_high_availability_process_date: The last_high_availability_process_date of this CtmServerDetails.  # noqa: E501
        :type: str
        """

        self._last_high_availability_process_date = last_high_availability_process_date

    @property
    def additional_attributes(self):
        """Gets the additional_attributes of this CtmServerDetails.  # noqa: E501

        Additional Attributes  # noqa: E501

        :return: The additional_attributes of this CtmServerDetails.  # noqa: E501
        :rtype: list[AdditionalAttribute]
        """
        return self._additional_attributes

    @additional_attributes.setter
    def additional_attributes(self, additional_attributes):
        """Sets the additional_attributes of this CtmServerDetails.

        Additional Attributes  # noqa: E501

        :param additional_attributes: The additional_attributes of this CtmServerDetails.  # noqa: E501
        :type: list[AdditionalAttribute]
        """

        self._additional_attributes = additional_attributes

    @property
    def services(self):
        """Gets the services of this CtmServerDetails.  # noqa: E501


        :return: The services of this CtmServerDetails.  # noqa: E501
        :rtype: list[CtmService]
        """
        return self._services

    @services.setter
    def services(self, services):
        """Sets the services of this CtmServerDetails.


        :param services: The services of this CtmServerDetails.  # noqa: E501
        :type: list[CtmService]
        """

        self._services = services

    @property
    def database_def(self):
        """Gets the database_def of this CtmServerDetails.  # noqa: E501


        :return: The database_def of this CtmServerDetails.  # noqa: E501
        :rtype: DatabaseDef
        """
        return self._database_def

    @database_def.setter
    def database_def(self, database_def):
        """Sets the database_def of this CtmServerDetails.


        :param database_def: The database_def of this CtmServerDetails.  # noqa: E501
        :type: DatabaseDef
        """

        self._database_def = database_def

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CtmServerDetails, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CtmServerDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
