# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.21.340
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CTMJobExecutedCounter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'server': 'str',
        'job_execution': 'int'
    }

    attribute_map = {
        'server': 'server',
        'job_execution': 'jobExecution'
    }

    def __init__(self, server=None, job_execution=None):  # noqa: E501
        """CTMJobExecutedCounter - a model defined in Swagger"""  # noqa: E501
        self._server = None
        self._job_execution = None
        self.discriminator = None
        if server is not None:
            self.server = server
        if job_execution is not None:
            self.job_execution = job_execution

    @property
    def server(self):
        """Gets the server of this CTMJobExecutedCounter.  # noqa: E501


        :return: The server of this CTMJobExecutedCounter.  # noqa: E501
        :rtype: str
        """
        return self._server

    @server.setter
    def server(self, server):
        """Sets the server of this CTMJobExecutedCounter.


        :param server: The server of this CTMJobExecutedCounter.  # noqa: E501
        :type: str
        """

        self._server = server

    @property
    def job_execution(self):
        """Gets the job_execution of this CTMJobExecutedCounter.  # noqa: E501


        :return: The job_execution of this CTMJobExecutedCounter.  # noqa: E501
        :rtype: int
        """
        return self._job_execution

    @job_execution.setter
    def job_execution(self, job_execution):
        """Sets the job_execution of this CTMJobExecutedCounter.


        :param job_execution: The job_execution of this CTMJobExecutedCounter.  # noqa: E501
        :type: int
        """

        self._job_execution = job_execution

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CTMJobExecutedCounter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CTMJobExecutedCounter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
