# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.21.340
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CtmSecTableSecAttrType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'delete': 'str',
        'read': 'str',
        'update': 'str',
        'order': 'str'
    }

    attribute_map = {
        'name': 'Name',
        'delete': 'Delete',
        'read': 'Read',
        'update': 'Update',
        'order': 'Order'
    }

    def __init__(self, name=None, delete=None, read=None, update=None, order=None):  # noqa: E501
        """CtmSecTableSecAttrType - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._delete = None
        self._read = None
        self._update = None
        self._order = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if delete is not None:
            self.delete = delete
        if read is not None:
            self.read = read
        if update is not None:
            self.update = update
        if order is not None:
            self.order = order

    @property
    def name(self):
        """Gets the name of this CtmSecTableSecAttrType.  # noqa: E501

        Table Name  # noqa: E501

        :return: The name of this CtmSecTableSecAttrType.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CtmSecTableSecAttrType.

        Table Name  # noqa: E501

        :param name: The name of this CtmSecTableSecAttrType.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def delete(self):
        """Gets the delete of this CtmSecTableSecAttrType.  # noqa: E501

        Values  Y N D for Yes No Default  # noqa: E501

        :return: The delete of this CtmSecTableSecAttrType.  # noqa: E501
        :rtype: str
        """
        return self._delete

    @delete.setter
    def delete(self, delete):
        """Sets the delete of this CtmSecTableSecAttrType.

        Values  Y N D for Yes No Default  # noqa: E501

        :param delete: The delete of this CtmSecTableSecAttrType.  # noqa: E501
        :type: str
        """

        self._delete = delete

    @property
    def read(self):
        """Gets the read of this CtmSecTableSecAttrType.  # noqa: E501

        Values  Y N D for Yes No Default  # noqa: E501

        :return: The read of this CtmSecTableSecAttrType.  # noqa: E501
        :rtype: str
        """
        return self._read

    @read.setter
    def read(self, read):
        """Sets the read of this CtmSecTableSecAttrType.

        Values  Y N D for Yes No Default  # noqa: E501

        :param read: The read of this CtmSecTableSecAttrType.  # noqa: E501
        :type: str
        """

        self._read = read

    @property
    def update(self):
        """Gets the update of this CtmSecTableSecAttrType.  # noqa: E501

        Values  Y N D for Yes No Default  # noqa: E501

        :return: The update of this CtmSecTableSecAttrType.  # noqa: E501
        :rtype: str
        """
        return self._update

    @update.setter
    def update(self, update):
        """Sets the update of this CtmSecTableSecAttrType.

        Values  Y N D for Yes No Default  # noqa: E501

        :param update: The update of this CtmSecTableSecAttrType.  # noqa: E501
        :type: str
        """

        self._update = update

    @property
    def order(self):
        """Gets the order of this CtmSecTableSecAttrType.  # noqa: E501

        Values  Y N D for Yes No Default  # noqa: E501

        :return: The order of this CtmSecTableSecAttrType.  # noqa: E501
        :rtype: str
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this CtmSecTableSecAttrType.

        Values  Y N D for Yes No Default  # noqa: E501

        :param order: The order of this CtmSecTableSecAttrType.  # noqa: E501
        :type: str
        """

        self._order = order

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CtmSecTableSecAttrType, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CtmSecTableSecAttrType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
