# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.21.340
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DeployBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'definitions_file': 'str',
        'deploy_descriptor_file': 'str',
        'additional_configuration': 'str'
    }

    attribute_map = {
        'definitions_file': 'definitionsFile',
        'deploy_descriptor_file': 'deployDescriptorFile',
        'additional_configuration': 'additionalConfiguration'
    }

    def __init__(self, definitions_file=None, deploy_descriptor_file=None, additional_configuration=None):  # noqa: E501
        """DeployBody - a model defined in Swagger"""  # noqa: E501
        self._definitions_file = None
        self._deploy_descriptor_file = None
        self._additional_configuration = None
        self.discriminator = None
        self.definitions_file = definitions_file
        if deploy_descriptor_file is not None:
            self.deploy_descriptor_file = deploy_descriptor_file
        if additional_configuration is not None:
            self.additional_configuration = additional_configuration

    @property
    def definitions_file(self):
        """Gets the definitions_file of this DeployBody.  # noqa: E501

        A file that contains definitions to be deployed to the server. Can be either a JSON definition file, an XML definition file, or a zip file that contains multiple JSON or XML definition files.  # noqa: E501

        :return: The definitions_file of this DeployBody.  # noqa: E501
        :rtype: str
        """
        return self._definitions_file

    @definitions_file.setter
    def definitions_file(self, definitions_file):
        """Sets the definitions_file of this DeployBody.

        A file that contains definitions to be deployed to the server. Can be either a JSON definition file, an XML definition file, or a zip file that contains multiple JSON or XML definition files.  # noqa: E501

        :param definitions_file: The definitions_file of this DeployBody.  # noqa: E501
        :type: str
        """
        if definitions_file is None:
            raise ValueError("Invalid value for `definitions_file`, must not be `None`")  # noqa: E501

        self._definitions_file = definitions_file

    @property
    def deploy_descriptor_file(self):
        """Gets the deploy_descriptor_file of this DeployBody.  # noqa: E501

        Deploy Descriptor JSON file.  # noqa: E501

        :return: The deploy_descriptor_file of this DeployBody.  # noqa: E501
        :rtype: str
        """
        return self._deploy_descriptor_file

    @deploy_descriptor_file.setter
    def deploy_descriptor_file(self, deploy_descriptor_file):
        """Sets the deploy_descriptor_file of this DeployBody.

        Deploy Descriptor JSON file.  # noqa: E501

        :param deploy_descriptor_file: The deploy_descriptor_file of this DeployBody.  # noqa: E501
        :type: str
        """

        self._deploy_descriptor_file = deploy_descriptor_file

    @property
    def additional_configuration(self):
        """Gets the additional_configuration of this DeployBody.  # noqa: E501

        additionalConfiguration to enable skip testing for local connection profile  # noqa: E501

        :return: The additional_configuration of this DeployBody.  # noqa: E501
        :rtype: str
        """
        return self._additional_configuration

    @additional_configuration.setter
    def additional_configuration(self, additional_configuration):
        """Sets the additional_configuration of this DeployBody.

        additionalConfiguration to enable skip testing for local connection profile  # noqa: E501

        :param additional_configuration: The additional_configuration of this DeployBody.  # noqa: E501
        :type: str
        """

        self._additional_configuration = additional_configuration

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DeployBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeployBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
