# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.21.340
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EMParams(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'desired_state': 'str',
        'additional_parameters': 'str',
        'check_interval': 'int'
    }

    attribute_map = {
        'desired_state': 'desiredState',
        'additional_parameters': 'additionalParameters',
        'check_interval': 'checkInterval'
    }

    def __init__(self, desired_state=None, additional_parameters=None, check_interval=None):  # noqa: E501
        """EMParams - a model defined in Swagger"""  # noqa: E501
        self._desired_state = None
        self._additional_parameters = None
        self._check_interval = None
        self.discriminator = None
        if desired_state is not None:
            self.desired_state = desired_state
        if additional_parameters is not None:
            self.additional_parameters = additional_parameters
        if check_interval is not None:
            self.check_interval = check_interval

    @property
    def desired_state(self):
        """Gets the desired_state of this EMParams.  # noqa: E501

        State of the EM component.  # noqa: E501

        :return: The desired_state of this EMParams.  # noqa: E501
        :rtype: str
        """
        return self._desired_state

    @desired_state.setter
    def desired_state(self, desired_state):
        """Sets the desired_state of this EMParams.

        State of the EM component.  # noqa: E501

        :param desired_state: The desired_state of this EMParams.  # noqa: E501
        :type: str
        """

        self._desired_state = desired_state

    @property
    def additional_parameters(self):
        """Gets the additional_parameters of this EMParams.  # noqa: E501

        Alternative startup parameters for the component.  # noqa: E501

        :return: The additional_parameters of this EMParams.  # noqa: E501
        :rtype: str
        """
        return self._additional_parameters

    @additional_parameters.setter
    def additional_parameters(self, additional_parameters):
        """Sets the additional_parameters of this EMParams.

        Alternative startup parameters for the component.  # noqa: E501

        :param additional_parameters: The additional_parameters of this EMParams.  # noqa: E501
        :type: str
        """

        self._additional_parameters = additional_parameters

    @property
    def check_interval(self):
        """Gets the check_interval of this EMParams.  # noqa: E501

        Interval in seconds to check the component's status.  # noqa: E501

        :return: The check_interval of this EMParams.  # noqa: E501
        :rtype: int
        """
        return self._check_interval

    @check_interval.setter
    def check_interval(self, check_interval):
        """Sets the check_interval of this EMParams.

        Interval in seconds to check the component's status.  # noqa: E501

        :param check_interval: The check_interval of this EMParams.  # noqa: E501
        :type: int
        """

        self._check_interval = check_interval

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EMParams, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EMParams):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
