# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.21.340
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FixedSubFolder(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'access_level': 'str',
        'operation': 'str',
        'original_name': 'str'
    }

    attribute_map = {
        'name': 'name',
        'access_level': 'accessLevel',
        'operation': 'operation',
        'original_name': 'originalName'
    }

    def __init__(self, name=None, access_level=None, operation=None, original_name=None):  # noqa: E501
        """FixedSubFolder - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._access_level = None
        self._operation = None
        self._original_name = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if access_level is not None:
            self.access_level = access_level
        if operation is not None:
            self.operation = operation
        if original_name is not None:
            self.original_name = original_name

    @property
    def name(self):
        """Gets the name of this FixedSubFolder.  # noqa: E501


        :return: The name of this FixedSubFolder.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FixedSubFolder.


        :param name: The name of this FixedSubFolder.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def access_level(self):
        """Gets the access_level of this FixedSubFolder.  # noqa: E501

        Access level of fixed subfolder - Read only, Write only, Full control  # noqa: E501

        :return: The access_level of this FixedSubFolder.  # noqa: E501
        :rtype: str
        """
        return self._access_level

    @access_level.setter
    def access_level(self, access_level):
        """Sets the access_level of this FixedSubFolder.

        Access level of fixed subfolder - Read only, Write only, Full control  # noqa: E501

        :param access_level: The access_level of this FixedSubFolder.  # noqa: E501
        :type: str
        """

        self._access_level = access_level

    @property
    def operation(self):
        """Gets the operation of this FixedSubFolder.  # noqa: E501

        deleteDefinition, deleteContent, rename. If no value - adding new fixedSubFolder  # noqa: E501

        :return: The operation of this FixedSubFolder.  # noqa: E501
        :rtype: str
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """Sets the operation of this FixedSubFolder.

        deleteDefinition, deleteContent, rename. If no value - adding new fixedSubFolder  # noqa: E501

        :param operation: The operation of this FixedSubFolder.  # noqa: E501
        :type: str
        """

        self._operation = operation

    @property
    def original_name(self):
        """Gets the original_name of this FixedSubFolder.  # noqa: E501

        populated only in case when operation = rename. Contains original name  # noqa: E501

        :return: The original_name of this FixedSubFolder.  # noqa: E501
        :rtype: str
        """
        return self._original_name

    @original_name.setter
    def original_name(self, original_name):
        """Sets the original_name of this FixedSubFolder.

        populated only in case when operation = rename. Contains original name  # noqa: E501

        :param original_name: The original_name of this FixedSubFolder.  # noqa: E501
        :type: str
        """

        self._original_name = original_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FixedSubFolder, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FixedSubFolder):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
