# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.21.340
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RunCommandActionData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'action_fails_behaviour': 'ActionFailsBehaviourData',
        'command_path': 'str',
        'successful_return_codes': 'str'
    }

    attribute_map = {
        'action_fails_behaviour': 'actionFailsBehaviour',
        'command_path': 'commandPath',
        'successful_return_codes': 'successfulReturnCodes'
    }

    def __init__(self, action_fails_behaviour=None, command_path=None, successful_return_codes=None):  # noqa: E501
        """RunCommandActionData - a model defined in Swagger"""  # noqa: E501
        self._action_fails_behaviour = None
        self._command_path = None
        self._successful_return_codes = None
        self.discriminator = None
        if action_fails_behaviour is not None:
            self.action_fails_behaviour = action_fails_behaviour
        if command_path is not None:
            self.command_path = command_path
        if successful_return_codes is not None:
            self.successful_return_codes = successful_return_codes

    @property
    def action_fails_behaviour(self):
        """Gets the action_fails_behaviour of this RunCommandActionData.  # noqa: E501


        :return: The action_fails_behaviour of this RunCommandActionData.  # noqa: E501
        :rtype: ActionFailsBehaviourData
        """
        return self._action_fails_behaviour

    @action_fails_behaviour.setter
    def action_fails_behaviour(self, action_fails_behaviour):
        """Sets the action_fails_behaviour of this RunCommandActionData.


        :param action_fails_behaviour: The action_fails_behaviour of this RunCommandActionData.  # noqa: E501
        :type: ActionFailsBehaviourData
        """

        self._action_fails_behaviour = action_fails_behaviour

    @property
    def command_path(self):
        """Gets the command_path of this RunCommandActionData.  # noqa: E501

        command or command path  # noqa: E501

        :return: The command_path of this RunCommandActionData.  # noqa: E501
        :rtype: str
        """
        return self._command_path

    @command_path.setter
    def command_path(self, command_path):
        """Sets the command_path of this RunCommandActionData.

        command or command path  # noqa: E501

        :param command_path: The command_path of this RunCommandActionData.  # noqa: E501
        :type: str
        """

        self._command_path = command_path

    @property
    def successful_return_codes(self):
        """Gets the successful_return_codes of this RunCommandActionData.  # noqa: E501

        successful return codes  # noqa: E501

        :return: The successful_return_codes of this RunCommandActionData.  # noqa: E501
        :rtype: str
        """
        return self._successful_return_codes

    @successful_return_codes.setter
    def successful_return_codes(self, successful_return_codes):
        """Sets the successful_return_codes of this RunCommandActionData.

        successful return codes  # noqa: E501

        :param successful_return_codes: The successful_return_codes of this RunCommandActionData.  # noqa: E501
        :type: str
        """

        self._successful_return_codes = successful_return_codes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RunCommandActionData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RunCommandActionData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
