# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.21.340
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ShoutDestination(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'address': 'str',
        'destination': 'str',
        'value': 'str',
        'value_list': 'list[ValueListItem]'
    }

    attribute_map = {
        'name': 'name',
        'address': 'address',
        'destination': 'destination',
        'value': 'value',
        'value_list': 'valueList'
    }

    def __init__(self, name=None, address=None, destination=None, value=None, value_list=None):  # noqa: E501
        """ShoutDestination - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._address = None
        self._destination = None
        self._value = None
        self._value_list = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if address is not None:
            self.address = address
        if destination is not None:
            self.destination = destination
        if value is not None:
            self.value = value
        if value_list is not None:
            self.value_list = value_list

    @property
    def name(self):
        """Gets the name of this ShoutDestination.  # noqa: E501

        Shout Destination name  # noqa: E501

        :return: The name of this ShoutDestination.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ShoutDestination.

        Shout Destination name  # noqa: E501

        :param name: The name of this ShoutDestination.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def address(self):
        """Gets the address of this ShoutDestination.  # noqa: E501

        Shout Destination address  # noqa: E501

        :return: The address of this ShoutDestination.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this ShoutDestination.

        Shout Destination address  # noqa: E501

        :param address: The address of this ShoutDestination.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def destination(self):
        """Gets the destination of this ShoutDestination.  # noqa: E501

        Shout Destination destination  # noqa: E501

        :return: The destination of this ShoutDestination.  # noqa: E501
        :rtype: str
        """
        return self._destination

    @destination.setter
    def destination(self, destination):
        """Sets the destination of this ShoutDestination.

        Shout Destination destination  # noqa: E501

        :param destination: The destination of this ShoutDestination.  # noqa: E501
        :type: str
        """

        self._destination = destination

    @property
    def value(self):
        """Gets the value of this ShoutDestination.  # noqa: E501

        Shout Destination value  # noqa: E501

        :return: The value of this ShoutDestination.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ShoutDestination.

        Shout Destination value  # noqa: E501

        :param value: The value of this ShoutDestination.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def value_list(self):
        """Gets the value_list of this ShoutDestination.  # noqa: E501

        Shout Destination value list  # noqa: E501

        :return: The value_list of this ShoutDestination.  # noqa: E501
        :rtype: list[ValueListItem]
        """
        return self._value_list

    @value_list.setter
    def value_list(self, value_list):
        """Sets the value_list of this ShoutDestination.

        Shout Destination value list  # noqa: E501

        :param value_list: The value_list of this ShoutDestination.  # noqa: E501
        :type: list[ValueListItem]
        """

        self._value_list = value_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ShoutDestination, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ShoutDestination):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
