# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.21.340
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SiteStandardInternalRule(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'rule_name': 'str',
        'restriction': 'SiteStandardRestriction'
    }

    attribute_map = {
        'rule_name': 'ruleName',
        'restriction': 'restriction'
    }

    def __init__(self, rule_name=None, restriction=None):  # noqa: E501
        """SiteStandardInternalRule - a model defined in Swagger"""  # noqa: E501
        self._rule_name = None
        self._restriction = None
        self.discriminator = None
        self.rule_name = rule_name
        if restriction is not None:
            self.restriction = restriction

    @property
    def rule_name(self):
        """Gets the rule_name of this SiteStandardInternalRule.  # noqa: E501


        :return: The rule_name of this SiteStandardInternalRule.  # noqa: E501
        :rtype: str
        """
        return self._rule_name

    @rule_name.setter
    def rule_name(self, rule_name):
        """Sets the rule_name of this SiteStandardInternalRule.


        :param rule_name: The rule_name of this SiteStandardInternalRule.  # noqa: E501
        :type: str
        """
        if rule_name is None:
            raise ValueError("Invalid value for `rule_name`, must not be `None`")  # noqa: E501

        self._rule_name = rule_name

    @property
    def restriction(self):
        """Gets the restriction of this SiteStandardInternalRule.  # noqa: E501


        :return: The restriction of this SiteStandardInternalRule.  # noqa: E501
        :rtype: SiteStandardRestriction
        """
        return self._restriction

    @restriction.setter
    def restriction(self, restriction):
        """Sets the restriction of this SiteStandardInternalRule.


        :param restriction: The restriction of this SiteStandardInternalRule.  # noqa: E501
        :type: SiteStandardRestriction
        """

        self._restriction = restriction

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SiteStandardInternalRule, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SiteStandardInternalRule):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
