# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.21.340
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SiteStandardPatternPart(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'part_type': 'str',
        'part_value': 'str'
    }

    attribute_map = {
        'part_type': 'partType',
        'part_value': 'partValue'
    }

    def __init__(self, part_type=None, part_value=None):  # noqa: E501
        """SiteStandardPatternPart - a model defined in Swagger"""  # noqa: E501
        self._part_type = None
        self._part_value = None
        self.discriminator = None
        self.part_type = part_type
        if part_value is not None:
            self.part_value = part_value

    @property
    def part_type(self):
        """Gets the part_type of this SiteStandardPatternPart.  # noqa: E501


        :return: The part_type of this SiteStandardPatternPart.  # noqa: E501
        :rtype: str
        """
        return self._part_type

    @part_type.setter
    def part_type(self, part_type):
        """Sets the part_type of this SiteStandardPatternPart.


        :param part_type: The part_type of this SiteStandardPatternPart.  # noqa: E501
        :type: str
        """
        if part_type is None:
            raise ValueError("Invalid value for `part_type`, must not be `None`")  # noqa: E501
        allowed_values = ["FixedText", "Field", "BusinessParameter", "InternalRule", "FreeText"]  # noqa: E501
        if part_type not in allowed_values:
            raise ValueError(
                "Invalid value for `part_type` ({0}), must be one of {1}"  # noqa: E501
                .format(part_type, allowed_values)
            )

        self._part_type = part_type

    @property
    def part_value(self):
        """Gets the part_value of this SiteStandardPatternPart.  # noqa: E501

        The value of the part. Its meaning depends on the part type - For FixedText - it is the part's fixed text For Field - it is the field name For BusinessParameter - it is the parameter name For InternalRule - it is the internal rule name  # noqa: E501

        :return: The part_value of this SiteStandardPatternPart.  # noqa: E501
        :rtype: str
        """
        return self._part_value

    @part_value.setter
    def part_value(self, part_value):
        """Sets the part_value of this SiteStandardPatternPart.

        The value of the part. Its meaning depends on the part type - For FixedText - it is the part's fixed text For Field - it is the field name For BusinessParameter - it is the parameter name For InternalRule - it is the internal rule name  # noqa: E501

        :param part_value: The part_value of this SiteStandardPatternPart.  # noqa: E501
        :type: str
        """

        self._part_value = part_value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SiteStandardPatternPart, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SiteStandardPatternPart):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
