# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.21.340
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SiteStandard(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'info': 'ItemInfo',
        'data': 'SiteStandardData'
    }

    attribute_map = {
        'info': 'info',
        'data': 'data'
    }

    def __init__(self, info=None, data=None):  # noqa: E501
        """SiteStandard - a model defined in Swagger"""  # noqa: E501
        self._info = None
        self._data = None
        self.discriminator = None
        self.info = info
        self.data = data

    @property
    def info(self):
        """Gets the info of this SiteStandard.  # noqa: E501


        :return: The info of this SiteStandard.  # noqa: E501
        :rtype: ItemInfo
        """
        return self._info

    @info.setter
    def info(self, info):
        """Sets the info of this SiteStandard.


        :param info: The info of this SiteStandard.  # noqa: E501
        :type: ItemInfo
        """
        if info is None:
            raise ValueError("Invalid value for `info`, must not be `None`")  # noqa: E501

        self._info = info

    @property
    def data(self):
        """Gets the data of this SiteStandard.  # noqa: E501


        :return: The data of this SiteStandard.  # noqa: E501
        :rtype: SiteStandardData
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this SiteStandard.


        :param data: The data of this SiteStandard.  # noqa: E501
        :type: SiteStandardData
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SiteStandard, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SiteStandard):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
