# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.21.340
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SupportedShoutDestinations(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'label': 'str',
        'values_list': 'list[SupportedShoutDestinations]'
    }

    attribute_map = {
        'type': 'type',
        'label': 'label',
        'values_list': 'valuesList'
    }

    def __init__(self, type=None, label=None, values_list=None):  # noqa: E501
        """SupportedShoutDestinations - a model defined in Swagger"""  # noqa: E501
        self._type = None
        self._label = None
        self._values_list = None
        self.discriminator = None
        if type is not None:
            self.type = type
        if label is not None:
            self.label = label
        if values_list is not None:
            self.values_list = values_list

    @property
    def type(self):
        """Gets the type of this SupportedShoutDestinations.  # noqa: E501

        Supported Shout Destination Addresses Validation type  # noqa: E501

        :return: The type of this SupportedShoutDestinations.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this SupportedShoutDestinations.

        Supported Shout Destination Addresses Validation type  # noqa: E501

        :param type: The type of this SupportedShoutDestinations.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def label(self):
        """Gets the label of this SupportedShoutDestinations.  # noqa: E501

        Supported Shout Destination Addresses Validation label  # noqa: E501

        :return: The label of this SupportedShoutDestinations.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this SupportedShoutDestinations.

        Supported Shout Destination Addresses Validation label  # noqa: E501

        :param label: The label of this SupportedShoutDestinations.  # noqa: E501
        :type: str
        """

        self._label = label

    @property
    def values_list(self):
        """Gets the values_list of this SupportedShoutDestinations.  # noqa: E501

        Supported Shout Destination Addresses validations values list - for address = group  # noqa: E501

        :return: The values_list of this SupportedShoutDestinations.  # noqa: E501
        :rtype: list[SupportedShoutDestinations]
        """
        return self._values_list

    @values_list.setter
    def values_list(self, values_list):
        """Sets the values_list of this SupportedShoutDestinations.

        Supported Shout Destination Addresses validations values list - for address = group  # noqa: E501

        :param values_list: The values_list of this SupportedShoutDestinations.  # noqa: E501
        :type: list[SupportedShoutDestinations]
        """

        self._values_list = values_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SupportedShoutDestinations, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SupportedShoutDestinations):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
