# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.21.340
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserConditionData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'company_names': 'list[str]',
        'user_or_group_names': 'list[str]'
    }

    attribute_map = {
        'company_names': 'companyNames',
        'user_or_group_names': 'userOrGroupNames'
    }

    def __init__(self, company_names=None, user_or_group_names=None):  # noqa: E501
        """UserConditionData - a model defined in Swagger"""  # noqa: E501
        self._company_names = None
        self._user_or_group_names = None
        self.discriminator = None
        if company_names is not None:
            self.company_names = company_names
        if user_or_group_names is not None:
            self.user_or_group_names = user_or_group_names

    @property
    def company_names(self):
        """Gets the company_names of this UserConditionData.  # noqa: E501

        array of company names  # noqa: E501

        :return: The company_names of this UserConditionData.  # noqa: E501
        :rtype: list[str]
        """
        return self._company_names

    @company_names.setter
    def company_names(self, company_names):
        """Sets the company_names of this UserConditionData.

        array of company names  # noqa: E501

        :param company_names: The company_names of this UserConditionData.  # noqa: E501
        :type: list[str]
        """

        self._company_names = company_names

    @property
    def user_or_group_names(self):
        """Gets the user_or_group_names of this UserConditionData.  # noqa: E501

        array of user or group names  # noqa: E501

        :return: The user_or_group_names of this UserConditionData.  # noqa: E501
        :rtype: list[str]
        """
        return self._user_or_group_names

    @user_or_group_names.setter
    def user_or_group_names(self, user_or_group_names):
        """Sets the user_or_group_names of this UserConditionData.

        array of user or group names  # noqa: E501

        :param user_or_group_names: The user_or_group_names of this UserConditionData.  # noqa: E501
        :type: list[str]
        """

        self._user_or_group_names = user_or_group_names

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserConditionData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserConditionData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
