# coding: utf-8

"""
    Control-M Services

    Provides access to BMC Control-M Services  # noqa: E501

    OpenAPI spec version: 9.21.340
    Contact: customer_support@bmc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WDAAgentsDataList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'agent_name': 'str',
        'ctm_server': 'str'
    }

    attribute_map = {
        'agent_name': 'agentName',
        'ctm_server': 'ctmServer'
    }

    def __init__(self, agent_name=None, ctm_server=None):  # noqa: E501
        """WDAAgentsDataList - a model defined in Swagger"""  # noqa: E501
        self._agent_name = None
        self._ctm_server = None
        self.discriminator = None
        if agent_name is not None:
            self.agent_name = agent_name
        if ctm_server is not None:
            self.ctm_server = ctm_server

    @property
    def agent_name(self):
        """Gets the agent_name of this WDAAgentsDataList.  # noqa: E501

        WDA eligible agents  # noqa: E501

        :return: The agent_name of this WDAAgentsDataList.  # noqa: E501
        :rtype: str
        """
        return self._agent_name

    @agent_name.setter
    def agent_name(self, agent_name):
        """Sets the agent_name of this WDAAgentsDataList.

        WDA eligible agents  # noqa: E501

        :param agent_name: The agent_name of this WDAAgentsDataList.  # noqa: E501
        :type: str
        """

        self._agent_name = agent_name

    @property
    def ctm_server(self):
        """Gets the ctm_server of this WDAAgentsDataList.  # noqa: E501

        Control-M/Server unique name  # noqa: E501

        :return: The ctm_server of this WDAAgentsDataList.  # noqa: E501
        :rtype: str
        """
        return self._ctm_server

    @ctm_server.setter
    def ctm_server(self, ctm_server):
        """Sets the ctm_server of this WDAAgentsDataList.

        Control-M/Server unique name  # noqa: E501

        :param ctm_server: The ctm_server of this WDAAgentsDataList.  # noqa: E501
        :type: str
        """

        self._ctm_server = ctm_server

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WDAAgentsDataList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WDAAgentsDataList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
